### PR TITLE
Wladiz2001 patch 1

### PR DESCRIPTION
**Pull request by wladiz2001**
Add verticalCentered option 

This option allows the modal to be centered vertically,
verticalCentered: true/false (default: false)

### CODE REVIEW

**Comment by GedMarc** [comment]
This looks great thank you! Seems like you got it all! :)

Which minify did you use for the .js min?

**Comment by wladiz2001** [comment]
I use UglifyJS 3 for minify, This tool decreases the size a little more than the one used previously.

**Comment by GedMarc** [comment]
ok i'm going to need to bring this in manually :) I can't risk doing an update where there may be malicious code in the min file, 

For reference, please only update the source files, we minify and build on our side before we set out a release, this is pretty standard practice

**Comment by GedMarc** [comment]
@wladiz2001 can you please remove the min file from the commit? find time stretched out sorry :(

**Comment by wladiz2001** [comment]
Ok, I delete de min files. Thanks for the explanation

**Pull request merged**
